<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
<!-- Blueprint for login form, here to make sure the function works, can be styled later -->
<h1>
    Login
</h1>

<form action="login" method="post">
    Email: <input name="email" type="text"><br>
    Password: <input name="password" type="text"><br>
    <input type="submit" value="Login">
</form>
</body>
</html>